VIA_ENABLE          = yes
VIAL_ENABLE         = yes
LTO_ENABLE          = yes

RGBLIGHT_ENABLE     = no
RGB_MATRIX_ENABLE   = no # Can't have RGBLIGHT and RGB_MATRIX at the same time.

OLED_ENABLE         = no

MOUSEKEY_ENABLE     = yes
EXTRAKEY_ENABLE     = yes
TAP_DANCE_ENABLE 	= yes
CAPS_WORD_ENABLE 	= yes
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE        = yes

QMK_SETTINGS        = yes

# trackpad
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
CIRQUE_PINNACLE_DIAMETER_MM = 40
CIRQUE_PINNACLE_POSITION_MODE = CIRQUE_PINNACLE_RELATIVE_MODE

# save space
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
MUSIC_ENABLE = no

TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no